%YAML:1.0

# we use TUM dataset, so set 0 for dataset input
INPUT_TYPE: 0

#GENERAL
# textureless area improvement
DO_GENERATE_DENSE_PCL: 1
DO_GAUSSIAN_SMOOTHING_BEFORE_CANNY: 1
DO_SHOW_DEBUG_IMAGE: 0
DO_USE_PANGOLIN_VIEWER: 1
USE_EDGE_HIST: 1

#Tracker
CHECK_TRACKING_RESULTS: 1
CHECK_INIT_VALUES: 1
USE_EDGE_FILTER: 1
N_FRAMES_HIST_VOTING: 3

#Output Settings
DO_OUTPUT_POSES: 1 #typically in TUM Format


